theme: jekyll-theme-cayman
title: Guillaume Prévost
description: ML portfolio


# Your name to show in the footer
author: Guillaume Prévost


menus:
    main:
    - Home: blabla
    - Archives: /archives/
    - About: /about/
    side:
    - Categories: /categories/
    - Tags: /tags/
